manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: scalaw4g
      url-base: https://github.com/scalaw4g
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # Tamago60 module
    - name: zmk-tamago60
      remote: scalaw4g
      revision: main
  self:
    path: config
